import { z } from "zod";

export const signalSchema = z.object({
  id: z.string(),
  title: z.string(),
  title_zh: z.string(),
  url: z.string().url(),
  published_at: z.string(),
  source_id: z.string(),
  source_name: z.string(),
  source_type: z.enum(["paper", "curated_papers", "product_update", "customer_case", "news", "community", "agent_project"]),
  primary_source: z.boolean(),
  stage: z.enum(["research", "product", "pilot", "production", "scale"]),
  evidence_grade: z.enum(["A", "B", "C", "D"]),
  evidence_score: z.number(),
  evidence_reason: z.string(),
  summary: z.string(),
  why_it_matters: z.string(),
  method: z.string(),
  result: z.string(),
  sector: z.string(),
  workflow: z.string(),
  metric: z.string(),
  metric_label: z.string(),
  opportunity: z.string(),
  topics: z.array(z.string()),
  ai_analyzed: z.boolean(),
});

export const siteDataSchema = z.object({
  meta: z.object({
    name: z.string(),
    generated_at: z.string(),
    timezone: z.literal("Asia/Shanghai"),
    site_url: z.string(),
    schedule: z.string(),
    health: z.enum(["ok", "warning", "stale"]),
    stale_after_hours: z.number(),
    raw_count: z.number(),
    shortlisted_count: z.number(),
    inserted_count: z.number(),
    total_items: z.number(),
    strong_items: z.number(),
    paper_items: z.number(),
    source_success: z.number(),
    source_attempted: z.number(),
    duration_seconds: z.number(),
  }),
  brief: z.object({
    headline: z.string(),
    summary: z.string(),
    themes: z.array(z.string()),
  }),
  stages: z.array(z.object({ key: z.enum(["research", "product", "pilot", "production", "scale"]), label: z.string(), count: z.number() })),
  trends: z.array(z.object({
    label: z.string(), current: z.number(), previous: z.number(),
    delta: z.number(), direction: z.enum(["up", "down", "flat"]),
  })),
  items: z.array(signalSchema).max(500),
  sources: z.array(z.object({
    id: z.string(), name: z.string(),
    source_type: z.enum(["paper", "curated_papers", "product_update", "customer_case", "news", "community", "agent_project"]),
    primary: z.boolean(),
    status: z.enum(["ok", "error", "not_run"]),
    count: z.number(), error: z.string(),
  })),
  methodology: z.object({ A: z.string(), B: z.string(), C: z.string(), D: z.string() }),
});
